
name: Teste Automatizado - Smoke Test
on: [ push ]

# on:
#   push:
#     branches: [ master ]

jobs:

    test:            
        runs-on: ubuntu-latest
        name: Teste automatizados
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.9'
            cache: 'pip' # caching pip dependencies
        - run: pip install robotframework
        - run: pip install -r requirements.txt
        - run: robot -d reports -v SALCELABS:False ./test/*.robot
        
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: reports
    
        - name: Gerando Reports
          uses: actions/download-artifact@v1
          with:
            name: reports

        - name: Send Slack notification
          uses: craftech-io/slack-action@v1
          with:
            slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
            slack_channel: nossa
            slack_username: Robozao
            status: success
            if: success()
            
        - name: Salvar relatórios
          uses: montudor/action-zip@v1
          with:
            args: zip -qq -r reports.zip reports
        - run:
            ls
       
        - name: Enviar arquivo HTML para o Slack
          run: |
            curl -F file=@reports.zip -F initial_comment="Mensagem opcional" -F channels=#brunou https://hooks.slack.com/services/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
