name: Teste Appium CI
on: [push]

#on:
#  pull_request:
#    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Intall Appium
        uses: moatazeldebsy/appium-server-gitHub-action@V1.0.4
        
      - name: Run Test
        run: robot -d logs /test/teste.robot