name: Robot Framework
on: [ push ]

# on:
#   push:
#     branches: [ master ]

jobs:

    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.9'
            cache: 'pip' # caching pip dependencies
        - run: pip install robotframework
        - run: pip install -r requirements.txt
        - run: robot -d reports -v SALCELABS:True ./test/*.robot

        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: reports
    
    generate_report:
        if: always()
        needs: [test] 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Download reports
          uses: actions/download-artifact@v1
          with:
            name: reports

    slackNotification:
        if: always()
        needs: [generate_report] 
        name: Slack Notification
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Slack Notification
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_CHANNEL: teste
            SLACK_COLOR: ${{ job.status }}
            SLACK_USERNAME: Robô de teste
            SLACK_ICON: https://cdn-icons-png.flaticon.com/512/1642/1642322.png?size=50
            SLACK_MESSAGE: 'Teste execultado com sucesso!'
            SLACK_TITLE: 'Teste execultado com sucesso!'
  
        # - name: Enviar notificação slack - Sucesso
        #   uses: drilonrecica/action-slack-notify@0.0.3
        #   if: ${{ success() }}
        #   env:
        #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        #     SLACK_CHANNEL: teste
        #     SLACK_COLOR: ${{ job.status }}
        #     SLACK_USERNAME: Robô de teste
        #     SLACK_ICON: https://cdn-icons-png.flaticon.com/512/1642/1642322.png?size=50
        #     SLACK_MESSAGE: 'Teste execultado com sucesso!'
        #     SLACK_TITLE: 'Teste execultado com sucesso!'
        
        # - name: Enviar notificação slack - Falha
        #   uses: drilonrecica/action-slack-notify@0.0.3
        #   if: ${{ failure() }}
        #   env:
        #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        #     SLACK_CHANNEL: teste
        #     SLACK_COLOR: ${{ job.status }}
        #     SLACK_USERNAME: Robô de teste
        #     SLACK_ICON: https://cdn-icons-png.flaticon.com/512/1642/1642322.png?size=50
        #     SLACK_MESSAGE: 'Teste execultado com falha!'
        #     SLACK_TITLE: 'Teste execultado com falha!'