name: Robot Framework
on: [ push ]

# on:
#   push:
#     branches: [ master ]

jobs:

    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.9'
            cache: 'pip' # caching pip dependencies
        - run: pip install robotframework
        - run: pip install -r requirements.txt
        - run: robot -d reports -v SALCELABS:True ./test/*.robot

        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: reports
    
    generate_report:
        if: always()
        needs: [test] 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Download reports
          uses: actions/download-artifact@v1
          with:
            name: reports

        - name: Enviar report teste slack - Sucesso
          id: slack
          uses: slackapi/slack-github-action@v1.23.0
          env:
            SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
            SLACK_COLOR: ${{ job.status }}

        - name: Enviar report teste slack - Falha
          id: slack
          uses: slackapi/slack-github-action@v1.23.0
          env:
            SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
            SLACK_COLOR: ${{ job.status }}

        - name: Enviar arquivo report slack
          uses: adrey/slack-file-upload-action@master
          with:
            path: reports.zip
            channel: teste