name: Robot Framework
on: [ push ]

# on:
#   push:
#     branches: [ master ]

jobs:

    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v4
          with:
            python-version: '3.9'
            cache: 'pip' # caching pip dependencies
        - run: pip install robotframework
        - run: pip install -r requirements.txt
        - run: robot -d reports -v SALCELABS:True ./test/*.robot

        - uses: joonvena/robotframework-docker-action@v1.0
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: reports
    
    generate_report:
        if: always()
        needs: [test] 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Download reports
          uses: actions/download-artifact@v1
          with:
            name: reports
        - name: Send report to commit
          uses: joonvena/robotframework-reporter-action@v2.1
          with:
            gh_access_token: ${{ secrets.GITHUB_TOKEN }}