name: Smoke Test Agendado
# on: [ push ]

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 10 * * 1,3,5

jobs:

    test:
        runs-on: ubuntu-latest
        name: Teste automatizados
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.9'
            cache: 'pip' # caching pip dependencies
        - run: pip install robotframework
        - run: pip install -r requirements.txt
        - run: robot -d reports -v SALCELABS:True ./test/*.robot

        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: reports
    
    generate_report:
        if: always()
        needs: [test]
        name: Gerando Reports
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Download reports
          uses: actions/download-artifact@v1
          with:
            name: reports

    slackNotification:
        if: always()
        needs: [generate_report] 
        name: Slack Notification
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        
        - name: Slack Notification - Sucesso
          uses: rtCamp/action-slack-notify@v2
          if: ${{ success() }}
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_CHANNEL: teste
            SLACK_COLOR: ${{ job.status }}
            SLACK_USERNAME: Robô de teste
            SLACK_ICON: https://cdn-icons-png.flaticon.com/512/1642/1642322.png?size=50
            SLACK_TITLE: 'Teste do PR execultado com sucesso! :white_check_mark:'

        - name: Slack Notification - Falha
          uses: rtCamp/action-slack-notify@v2
          if: ${{ failure() }}
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_CHANNEL: teste
            SLACK_COLOR: ${{ job.status }}
            SLACK_USERNAME: Robô de teste
            SLACK_ICON: https://cdn-icons-png.flaticon.com/512/1642/1642322.png?size=50
            SLACK_TITLE: 'Teste execultado com sucesso! :fire:'